# Generated by Django 5.0.2 on 2024-02-11 18:07

import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vackolo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bemutatkozas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(upload_to='app_brandon_photography/img/photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.CharField(default='Nagy Ádám', max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('extract', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
    ]
