# Generated by Django 5.0.2 on 2024-02-13 17:18

import django.db.models.deletion
import django_quill.fields
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vackolo', '0002_bemutatkozas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bemutatkozas',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='bemutatkozas',
            name='extract',
        ),
        migrations.RemoveField(
            model_name='bemutatkozas',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='bemutatkozas',
            name='title',
        ),
        migrations.RemoveField(
            model_name='bemutatkozas',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='bemutatkozas',
            name='user',
        ),
        migrations.CreateModel(
            name='BemutatkozasTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('content', django_quill.fields.QuillField()),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_vackolo.bemutatkozas')),
            ],
            options={
                'verbose_name': 'bemutatkozas Translation',
                'db_table': 'app_vackolo_bemutatkozas_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
