# Generated by Django 5.0.2 on 2024-02-13 20:37

import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vackolo', '0004_onkentesmunka_tamogatas_onkentesmunkatranslation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kapcsolat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefonszam', models.CharField(max_length=50)),
                ('nyitvatartas', models.CharField(max_length=50)),
                ('emailcim', models.CharField(default='', max_length=50)),
                ('telephely', models.CharField(default='', max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='tamogatas',
            name='adoszam',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='tamogatas',
            name='paypalemail',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='tamogatas',
            name='szamlaszam',
            field=models.CharField(default='', max_length=50),
        ),
    ]
