# Generated by Django 5.0.2 on 2024-02-13 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_vackolo', '0005_kapcsolat_tamogatas_adoszam_tamogatas_paypalemail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kapcsolat',
            name='telefonszam',
        ),
    ]
