# Generated by Django 4.0.3 on 2024-02-20 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vackolo', '0007_kapcsolat_facebookmessengercim'),
    ]

    operations = [
        migrations.AddField(
            model_name='kapcsolat',
            name='telephelyterkeplink',
            field=models.CharField(default='', max_length=50),
        ),
    ]
